sudo: false
language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.15 CC=gcc-4.8 CXX=g++-4.8

install:
    - source .ci/travis.sh
    - python setup.py develop

cache:
    directories:
        - $HOME/.theano
        - $HOME/miniconda

script:
    - py.test -v -s
