sudo: false
language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

env:
    global:
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable

matrix:
    include:
        - os: linux

        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.13

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14

        - os: osx

install:
    - export CXX=g++-4.8
    - export CC=gcc-4.8
    - source .ci/travis.sh
    - python setup.py develop

cache:
    directories:
        - $HOME/.theano
        - $HOME/miniconda

script:
    - py.test -v -s
